exclude: ^(src/|models/|tests/|notebooks|conf/)
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config", "setup.cfg", "--max-line-length", "115"]
        files: ^src/
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^src/
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        files: ^src/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^src/
      - id: check-yaml
        files: ^src/
      - id: check-toml
        files: ^src/
      - id: end-of-file-fixer
        files: ^src/
      - id: double-quote-string-fixer
        files: ^src/
      - id: requirements-txt-fixer
        files: ^src/
      - id: check-merge-conflict
        files: ^src/
      - id: fix-encoding-pragma
        args: ["--remove"]
        files: ^src/
      - id: mixed-line-ending
        args: ["--fix=lf"]
        files: ^src/
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "120", "--wrap-summaries", "120"]
        files: ^src/
