steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-central1-docker.pkg.dev/lovely-aurora-423308-i7/gcr.io/dvc_data:latest', '-f', 'dvcdata.dockerfile', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-central1-docker.pkg.dev/lovely-aurora-423308-i7/gcr.io/dvc_data:latest']
