n_epochs: 10
batch_size: 16
num_workers: 4
optimizer: AdamW
optimizer_params: {}
criterion: CrossEntropyLoss
criterion_params: {}
logging_freq: 100
accelerator: "gpu"
devices: 8
strategy: ddp
num_nodes: 1
