defaults:
  - dataset: celeba
  - model: unet
  - diffusion: ddpm
  - optimizer: adam

device: cuda

dataset:
  image_size: 32

model:
  image_channels: 3
  n_channels: 64
  channel_multipliers: [1, 2, 2, 4]
  is_attention: [false, false, false, true]

diffusion:
  n_steps: 1000

training:
  batch_size: 64
  n_samples: 16
  learning_rate: 2e-5
  epochs: 100

optimizer:
  type: adam
  betas: [0.9, 0.99]
  eps: 1e-8
